[tools]
python = "3.12"

[env.'_'.python]
venv = { path = ".venv", create = true }

[tasks.make-deps]
run = "pip-compile -v"
description = "Update dependencies"
sources = ["pyproject.toml"]
outputs = ["requirements.txt"]
depends = ["install-pip-tools"]

[tasks.install-deps]
run = "pip-sync requirements.txt"
description = "Install dependencies"
sources = ["requirements.txt"]
depends = ["install-pip-tools"]

[tasks.install-pip-tools]
run = "pip install pip-tools"

[tasks.dev]
run = "python manage.py runserver"
description = "Run the development server"

[tasks.migrate]
run = "python manage.py migrate"
description = "Apply database migrations"
depends = ["docker-dev"]

[tasks.docker-dev]
run = "docker compose up -d --wait"
description = "Run delopment server in docker"

[tasks.install-pre-commit]
run = "pre-commit install"
description = "Install pre-commit git hooks"
sources = [".pre-commit-config.yaml"]

[tasks.load-fixtures]
run = "python manage.py loaddata api/fixtures/*.yaml"
depends = ["migrate"]

[tasks.setup-dev]
description = "Setup development environment"
depends = ["install-deps", "install-pre-commit", "migrate", "load-fixtures"]
