# Generated by Django 5.0.6 on 2024-06-14 14:28

import django.db.models.deletion
import pgvector.django
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        CreateExtension(name="vectors"),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "pesel",
                    models.CharField(max_length=11, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FaceVector",
            fields=[
                (
                    "uuid",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("face_vector", pgvector.django.VectorField(dimensions=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_vectors",
                        to="persons.person",
                    ),
                ),
            ],
        ),
    ]
