# Generated by Django 5.0.6 on 2024-06-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="uuid",
            field=models.UUIDField(
                auto_created=True,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
