# Generated by Django 5.0.6 on 2024-06-15 16:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0002_alter_facevector_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facevector",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
