# Generated by Django 5.0.6 on 2024-06-15 17:46

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_alter_facevector_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="face_vector",
            field=pgvector.django.VectorField(blank=True, dimensions=1, null=True),
        ),
        migrations.DeleteModel(
            name="FaceVector",
        ),
    ]
