# Generated by Django 5.0.6 on 2024-06-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0004_person_face_vector_delete_facevector"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="driving_license_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="id_number",
            field=models.CharField(blank=True, null=True),
        ),
    ]
